//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReceivable
    {
        public int ID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReceivableAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
