//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Purchase_Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
